// This file is auto-generated by `supabase gen types typescript --linked`
// Run the script after connecting to your Supabase project.
// Placeholder types until you generate real ones from your schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type ClubEntry = {
  club: string;
  carry: number;
};

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          club_bag: ClubEntry[];
          created_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          club_bag?: ClubEntry[];
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      practice_sessions: {
        Row: {
          id: string;
          user_id: string;
          type: "block" | "random" | "mixed" | "game" | "planned";
          title: string;
          started_at: string;
          ended_at: string | null;
          duration_minutes: number | null;
          balls_used: number | null;
          overall_feel: number | null;
          notes: string | null;
          reflection: Json | null;
          config: Json | null;
          score: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: "block" | "random" | "mixed" | "game" | "planned";
          title: string;
          started_at?: string;
          ended_at?: string | null;
          duration_minutes?: number | null;
          balls_used?: number | null;
          overall_feel?: number | null;
          notes?: string | null;
          reflection?: Json | null;
          config?: Json | null;
          score?: number | null;
        };
        Update: Partial<Database["public"]["Tables"]["practice_sessions"]["Insert"]>;
      };
      // Add session_drills table here when you expand the schema
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
